version: "3.9"

services:
  migrator:
    image: ${IMAGE_URL}
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: none  # Не перезапускать при ошибке
      placement:
        constraints:
          - "node.role==worker"

networks:
  app-network:
    external: true
